### ISSUE TITLE
That's more on the new UI to handle 404 better, it's expected that nginx would send all traffic there.

### ISSUE THREAD

**Issue by mprat** [mitoc/mitoc-gear-ui#20]
That's more on the new UI to handle 404 better, it's expected that nginx would send all traffic there. 
The routing is done client-side in the React app, I can improve the behavior and add a 404 page. 

> One more weird thing - I think it's another nginx problem. In the V1 app, any URL that wasn't explicitly defined gave a "page not found" error, but with the V2 app, any URL works fine:
> 
> ```
> mitoc-gear.mit.edu/foobar/ --> fine
> mitoc-gear.mit.edu/ui-v1/foobar/ --> not found
> ```

_Originally posted by @fpagnoux in https://github.com/mitoc/geardb-ansible/issues/19#issuecomment-1107961959_

**Comment by fpagnoux** [comment]
Fixed by redirected unexpected routes to /people
