### ISSUE TITLE
Upgrade bootstrap 5.2.0 (not beta), remove pinned autoprefixer version

### ISSUE THREAD

**Issue by mprat** [mitoc/mitoc-gear-ui#30]
This warning (https://github.com/twbs/bootstrap/pull/36283) appears in CI when running `yarn build` when running with `"bootstrap": "^5.1.3"`. See #28.

When 5.2.0 release comes out for bootstrap, use that instead of the beta release.

**Comment by fpagnoux** [comment]
Fixed by 9f9129c82388e05346a6828fcc12dbff79c2a950
