### ISSUE TITLE
Desk credit workflow in the UI

### ISSUE THREAD

**Issue by mprat** [mitoc/mitoc-gear-ui#42]
Should move the desk credit flow into the UI itself rather than through a Google Form.

- [x] Form for requesting desk credit
- [x] Desk captain view that lists all requesting credit

Matching backend issue: https://github.com/mitoc/gear-db-django/issues/371

**Comment by mprat** [comment]
@fpagnoux per the email chain with desk captains about storing desk worker active status, I think this is the way to do it. Let me know what you think!

**Comment by fpagnoux** [comment]
Closed by https://github.com/mitoc/mitoc-gear-ui/pull/47
