### ISSUE TITLE
Feature request: don't show retired gear in "rent gear" tab

### ISSUE THREAD

**Issue by mprat** [mitoc/mitoc-gear-ui#43]
![Screenshot from 2022-07-15 21-19-21](https://user-images.githubusercontent.com/829379/179328898-958be0e6-b256-40c3-92ca-debd42ad8e9d.png)

In the image above, don't show the retired items in the search results - they aren't usually un-retired, so it takes up valuable real estate.

**Comment by fpagnoux** [comment]
Fixed in eff89efb40ce2a4424d1f0c2bf29755770afec4e
